markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Adam Leonard
url: http://adamjleonard.com
description: A blog about all teh things.
twitter: adamjleonard
github: adamjleonard
gravatar_url:
